name: Terraform Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  id-token: write

jobs:
  tests:
    name: Tests
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/test.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    with:
      service_account: plt-lz-testing-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_test_args: -var=app_key="BLAA" -var=api_key="BLAA"
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    # secrets:
    #   terraform_test_secret_args: >-
    #     -var=api_key=${{ secrets.DATADOG_API_KEY }}
    #     -var=app_key=${{ secrets.DATADOG_APP_KEY }}
